### ISSUE TITLE
Add more app spaces to the default home screen

### ISSUE THREAD

**Issue by dontfwiththestream** [jkuester/unlauncher#206] opened 2024-01-04 01:26 UTC
On larger devices, I feel it would be better to allow more applications to be visible on the home screen. Currently on my oneplus 7p i have 6 applications (the maximum). I have room for 10 at least

**Comment by jkuester** [comment] 2024-01-04 14:41
Agreed!  There is room for some good improvement here.  Ideally, I would like to try and come up with a way to limit the home apps based on the actual device screen size (instead of just hard-coding the value)...

All that said, I think this is pretty much a duplicate of https://github.com/jkuester/unlauncher/issues/89

**Closed** 2024-01-04 14:41 UTC
Labels: duplicate
