### ISSUE TITLE
Java SimpleDateFormat?

### ISSUE THREAD

**Issue by ja7833** [jkuester/unlauncher#39] opened 2021-02-28 19:21 UTC
I've been experimenting with all of the "minimal" launchers on F-Droid the last several days.  Unlauncher is my favorite.

The one enhancement I would request is an option to use Java SimpleDateFormats to create both the time **and** date format on the home screen. Forecastie https://f-droid.org/en/packages/cz.martykan.forecastie/ as an example has a "Custom Date Format" option using SimpleDateFormats.

Currently my date displays as "Sun, _M02_ 28" which is not a format I am accustomed to.

Thanks jkuester for your efforts in creating a clean and simple Android launcher experience.

**Comment by jkuester** [comment] 2021-03-01 03:02
Thank you for the kind words and for taking the time to log a helpful issue with an example!  

Actually, this date format weirdness is caused by some locale changes that were made in Android 11.  A recent (but as of yet unreleased PR) has hopefully fixed this issue: https://github.com/jkuester/unlauncher/pull/35

As of that PR, the date format in Unlauncher should be set to the device's default local (via the SimpleDateFormat).  I hope to get that change released soon!

**Comment by jkuester** [comment] 2021-07-06 22:29
Closing this since it should have been resolved in `v1.1.0`.  Please reopen this issue if the problem still persists on the latest version of Unlauncher.

**Closed by jkuester** 2021-07-06 22:29 UTC
