### ISSUE TITLE
Reddit client infinity doesn't show up

### ISSUE THREAD

**Issue by mionami** [jkuester/unlauncher#100] opened 2022-01-10 10:20 UTC
I cannot access infinity

**Comment by jkuester** [comment] 2022-01-10 14:11
Couple of questions since I have not been able to reproduce this locally yet.  

- Where did you install Infinity from?  (Play Store, F-Droid, apk...)
- Did you install Infinity before or after installing and running Unlauncher?

**Comment by jkuester** [comment] 2022-02-17 22:15
Closing since this is a duplicate of #96

**Closed by jkuester** 2022-02-17 22:15 UTC
