### ISSUE TITLE
Work profile issue

### ISSUE THREAD

**Issue by reyfernando81** [jkuester/unlauncher#25] opened 2020-11-13 17:04 UTC
The list shows the work profile`s apps but doesn`t launch any app from the work profile. Only launchs this apps if they are added to the main screen and launched from there. Great launche anyway.

**Comment by jkuester** [comment] 2020-12-01 02:22
Thank you for the feedback!  I am pretty sure this is a duplicate of https://github.com/jkuester/unlauncher/issues/11

There are some known issues with Work Profiles that need to be addressed.

**Closed** 2020-12-01 02:22 UTC
Labels: duplicate
