### ISSUE TITLE
[Feature Request] Allow to configure distance between apps in listing

### ISSUE THREAD

**Issue by bserem** [jkuester/unlauncher#97] opened 2021-12-04 20:39 UTC
Love the idea behind unlauncher and I'd like to see it get better and better.

However, for big thumbs it gets kind of tricky to use. It would be great to allow more spacing between apps in the app list.
Hopefully this is an easy change.

Thanks

**Comment by jkuester** [comment] 2021-12-06 17:37
Thank you for the suggestion @bserem!  To clarify, are you wanting more spacing on the home screen (between the 6 pinned apps) or between the apps in the app drawer (or both)?  

Also, I think this issue is a duplicate of #74, so I am going to close it for now. But feel free to reopen if you think this is a different ask.

**Closed by jkuester** 2021-12-06 17:37 UTC
