### ISSUE TITLE
App list closes when swiping up

### ISSUE THREAD

**Issue by Donkey-Doug** [jkuester/unlauncher#73] opened 2021-07-19 13:53 UTC
When swiping up in the app list, the drawer closes instead of swiping to the top of the list.

See video:

https://user-images.githubusercontent.com/50382414/126170942-f0e3a2e1-967b-44ef-9f9b-434b28538f74.mp4

**Comment by jkuester** [comment] 2021-07-20 13:27
So, technically this "works as intended".  Meaning, that when you swipe back up in the app drawer, it will scroll to the top of the drawer and then keep scrolling out of the drawer and back to the home screen.  (So you can scroll back up to the apps at the top of the drawer, but if you scroll too far or with too much momentum then it will just end up closing the drawer).

I guess there are other ways that this could behave (stopping/slowing at the top of the app drawer, etc), but as far as I know, none of them would be very simple to implement with the MotionLayout that we are currently using.  Additionally, I personally prefer being able to "flick" your way out of the app drawer and back to the home screen without requiring additional taps or gestures.  Even if you do not share my preference on this, hopefully this behavior will be less annoying when #70 is addressed (and also #24).

**Closed by jkuester** 2021-07-20 13:27 UTC

**Comment by Donkey-Doug** [comment] 2021-07-20 13:55
A quick swipe up should close it. A regular or short swipe up should move to the top. Moving to the top is not possible. It always closes.

**Comment by Donkey-Doug** [comment] 2021-07-24 21:12
Did you look at the video? It is impossible to swipe up again. If I scrolled past an app, I need to close and reopen the drawer. I do believe this is a bug that needs to be fixed.
